### ISSUE TITLE
Crash on .commitEdit event when trying to delete a row with .delete editStyle.

### ISSUE THREAD

**Issue by Ignakas** [malcommac/Owl#1]
Hi,
I am trying to delete a row from my table using _.delete_ editStyle and the app is crashing due to `Fatal error: Index out of range`. By the looks of it the datasource gets updated before the tableView finishes editing and _director_ tries to access model at indexPath(in `didEndEditingRowAt:` method) which was already deleted.

To reproduce the issue - add the lines below into CatalogViewController of OwlDemo app. 
What's the correct way to delete a row from a table?

```swift
catalogAdapter.events.editStyle = { ctx in
    return .delete
}

catalogAdapter.events.canEditRow = { ctx in
    return true
}

catalogAdapter.events.deleteConfirmTitle = { ctx in
    return "Delete"
}

catalogAdapter.events.commitEdit = { [weak self] ctx, style in
    guard let indexPath = ctx.indexPath else { return }
    self?.tableDirector?.sections[indexPath.section].remove(at: indexPath.row)
    self?.tableDirector?.reload()
}
```

**Comment by malcommac** [comment]
Hi, Thank you for your report.
I've just fixed this issue but in order to correctly receive events for end editing model and cell you mus enclose the function inside an editing session:

That's the code:

```swift
catalogAdapter.events.commitEdit = { [weak self] ctx, style in
  guard let indexPath = ctx.indexPath else { return }
  self?.tableDirector?.reload(afterUpdate: { dir in
    dir.sections[indexPath.section].remove(at: indexPath.row)
    return UITableView.RowAnimation.none
  }, completion: nil)
}
```
