### ISSUE TITLE
[TableDirector/CollectionDirector] `elementAt` gives back the wrong element

### ISSUE THREAD

**Issue by geraldeersteling** [malcommac/Owl#15]
I've discovered a but in the function `elementAt` (L:267) in the `TableDirector`.

The function returns the same element because the return value uses the wrong index to search the elements array. Here is the current line which returns the element:

`return sections[indexPath.section].elements[indexPath.section]`

I think the index in the `elements` array should be `indexPath.row`.

**Comment by geraldeersteling** [comment]
I realised I could also fork your repo and try to fix it myself; as such, I made a MR

**EDIT:**
Also fixed it in `CollectionDirector`

**Comment by malcommac** [comment]
Fixes merged! thanks.
