### ISSUE TITLE
TableAdapter Element Nullability

### ISSUE THREAD

**Issue by wow-such-amazing** [malcommac/Owl#18]
Hi again!)

I didn't have time to go deep. But I found that element in CollectionAdapter events is non-optional while in TableAdapter events it is optional. And that increases the difficulty to switch from FlowKitManager plus it forces to add guards and if statements. Or for example if CellModel contains the height of the cell developer have to create some default value.

What is the reason behind the idea that TableAdapter events contains optional element?

Thank you a lot for keep improving this library!

**Comment by malcommac** [comment]
it's related to the cachedContext which save data for didEndDisplay and I'm missing it from the CollectionAdapter's Event counterpart. Anyway it should be not necessary anymore so I've removed the nullability from the TableAdapter's Event.
