### ISSUE TITLE
CollectionDirector.Event/TableDirector.Event collection/collectionSize - table/tableSize are nil

### ISSUE THREAD

**Issue by zdnk** [malcommac/Owl#23]
Hello,
the `itemSize` event `Context` has always `collectionView` and and `collectionSize` properties `nil` which is annoying if you want to make layout with even rows or columns.

**Comment by CureleaAndrei** [comment]
> Hello,
> the `itemSize` event `Context` has always `collectionView` and and `collectionSize` properties `nil` which is annoying if you want to make layout with even rows or columns.

Hi, have you found a solution for this ?

**Comment by david1824** [comment]
Hi, just upgraded from FlowKit and still resolving issues.
One of my cells requires height calculation based on parent `UITableView`, however the `rowHeight` callback receives nil in `table` property of `Event`. It receives `cell`, but `superview` of `cell` is nil somehow.
As I understand, FlowKit handled `container` property in `InternalContext` from the start of cell initialisation and passed it to `Event` separately, thus we had `cell` and `table` in the `Event`. I can't find commit about this change and its purpose and however it dramaticaly affects current height calculation, cause rowHeight callback does not receives parent tableView through cell or adapter and there is no other way to access to it.
Any suggestions?
