### ISSUE TITLE
Extending CollectionCellAdapter; set the class as open

### ISSUE THREAD

**Issue by CureleaAndrei** [malcommac/Owl#25]
Hi, I am trying to extend CollectionCellAdapter so that all the logic that i want for this adapter to be encapsulated in a specific class. Doing so i get the folowing error : "Cannot inherit from non-open class 'CollectionCellAdapter<TrainingDayModel, DayCell>' outside of its defining module". Is there a way to extend CollectionCellAdapter? 

P.S. : In the last library FlowKit you could do this

Ty, for this great library

**Comment by malcommac** [comment]
`CollectionCellAdapter` is now open and subclassable.
Thanks for your report.
