### ISSUE TITLE
ScrollViewEventsHandler is not public and can't be accessed to listen scroll events

### ISSUE THREAD

**Issue by CureleaAndrei** [malcommac/Owl#26]
Hi, I am trying to set scrollview delegates on a FlowCollectionDirector, folowing the readme. I can get only to the scrollEvents property but when i try to acces any of it's delegates i get an error like this : 'didScroll' is inaccessible due to 'internal' protection level.

I think the problem is that for ScrollViewEventsHandler properties there is no public access modifier and the default is internal. If this is the desired behavior, can you please explain how can we set those delegates? 

Ty for this great library! It's really helpfull

**Comment by bunnyhero** [comment]
I'm having this issue too. IMHO the members of `ScrollViewEventsHandler` should be `public`, otherwise I don't see any reason for them to exist. This is a real blocker for me right now :(

**Comment by bunnyhero** [comment]
I see this has been fixed on the develop branch: ee4ffff5cf7ec93df3a78901727760835019755a

Is there any way I can help the CocoaPod get updated with this fix? Thanks :)

**Comment by CureleaAndrei** [comment]
Hi, any news on this ? It is merged?

**Comment by malcommac** [comment]
I’ll be back from holidays next week and I’ll look at this ASAP. Thanks for the patience

**Comment by CureleaAndrei** [comment]
No problem. Have a nice Holiday 😄.
