### ISSUE TITLE
Header/Footer adapters registration

### ISSUE THREAD

**Issue by wow-such-amazing** [malcommac/Owl#28]
Hi :) 

In the FlowKit we didn't need to register header/footer adapters. However it has changed in OwlKit. Why do we need to do this?

Before I had the following code:
```
import FlowKitManager

public class SomeHeaderAdapter: TableSectionView<SomeHeaderView> {

    public init(config: SomeHeaderConfig) {
        super.init()

        on.height = { _ in
            return 32
        }

        on.dequeue = { context in
            context.view?.layout(with: config)
            context.view?.section = context.section
        }
    }
}
```

Now I'm not sure if I can do it this way. And I'm wondering how should I pass data to the header view 🤔

**Comment by wow-such-amazing** [comment]
It seems weird that in TableDirector's method
```
func registerHeaderFooterAdapters(_ adapters: [TableHeaderFooterAdapterProtocol])
```
and in TableSection's initialiser
```
init(id: String? = nil, elements: [ElementRepresentable] = [], headerView: TableHeaderFooterAdapterProtocol?, footerView: TableHeaderFooterAdapterProtocol?) 
```
we have the same type to pass inside.

**Comment by malcommac** [comment]
it's the same approach used for cells which has its own adapter, you can register it (if needed, typically when getting them from an external xib) then use it by assigning to a section.
Change is to homologate the behaviour.
