### ISSUE TITLE
[TableSection] How to set section titles for UITableView?

### ISSUE THREAD

**Issue by onmyway133** [malcommac/Owl#3]
Hi, congrats on the new tool. I have a question, in UITableView, I can use `titleForHeaderInSection`, how to do that with Owl?

**Comment by malcommac** [comment]
Hi @onmyway133 , thank you very much.
Regards your question: adding index title to a section is pretty simple, you need just use the `indexTitle` property of the target `TableSection` instance.

So, for example:

```swift
let sectionContactsA = tableDirector?.add(elements: [user1, user2,....])
sectionContactsA?.indexTitle = "A" 
```

Owl automatically adds the title into the right index lists of the table; only section instances with a non nil `indexTitle` property will became part of the list. Click icon to jump on it is automatically made by Owl so you don't need to set anything special.
Hope it helps.

**Comment by onmyway133** [comment]
@malcommac cool, that helps 👍
