### ISSUE TITLE
Crash in didEndDisplaying cell call

### ISSUE THREAD

**Issue by r00li** [malcommac/Owl#38]
Hi!
I've just implemented this library into my app (the latest version) and it works great, except for one problem - it crashes during reload operations in the didEndDisplaying cell call.

The crash actually happens inside the `let (model, adapter) = context(forItemAt: indexPath)` call with the `Index out of range` error. What happens is that it is trying to access a cell that is no longer in that section.

This happens when I call reload with a new data model... The differences are - one cell gets moved from section 1 to section 2 (and needs to be reloaded), and the now top cell inside section 1 needs to be reloaded as well. Funny thing is that the update actually completes. The crash occurs after the completion handler is called (and I see cells finish moving correctly).

I temporarily solved this issue by adding this inside the didEndDisplaying cell function:
```        
guard indexPath.section < sections.count, indexPath.row < sections[indexPath.section].elements.count else {
    return
}
```

This solves the problem, although I don't really think that this is the correct solution.

**Comment by CureleaAndrei** [comment]
I can relate to this problem. I've been bumping into something like this. When i want to reload with an empty new data model the error "Index out of range" occurs.

**Comment by zdnk** [comment]
same here, any update @malcommac ?

**Comment by CureleaAndrei** [comment]
> I temporarily solved this issue by adding this inside the didEndDisplaying cell function:

Hello, can you please help me with the workaround you described ?

**Comment by r00li** [comment]
> > I temporarily solved this issue by adding this inside the didEndDisplaying cell function:
> 
> Hello, can you please help me with the workaround you described ?

Basically open the TableDirector.swift inside OwlKit, find the `public func tableView(_ tableView: UITableView, didEndDisplaying cell: UITableViewCell, forRowAt indexPath: IndexPath)`method and paste in the above guard snippet before anything else. This will prevent this method from crashing.

**Comment by andriigua** [comment]
@malcommac could you please address this issue as it happens quite often when you constantly change sections elements?
Or if there is a need I can handle it and create for you the pull request

P.S. I believe the same crash will be present for the collectiondirector  as the general logic stays the same - we are trying to access the old context elements after the context was changed

**Comment by CureleaAndrei** [comment]
> @malcommac could you please address this issue as it happens quite often when you constantly change sections elements?
> Or if there is a need I can handle it and create for you the pull request
> 
> P.S. I believe the same crash will be present for the collectiondirector as the general logic stays the same - we are trying to access the old context elements after the context was changed

Exactly, I can confirm that the same happens for the collectiondirector

**Comment by malcommac** [comment]
I've fixed the bug but I need to make the `element: Model` property of the `TableCellAdapter.Event` and `CollectionCellAdapter.Event` optional because in these situations I can't get the model instance for removed items (previously I made an internal cache to keep these items floating around but frankly its a bit overkill and introduces several weak points).
Thanks for reporting the issue.
